# ------------------------------------------------------------------------------
# CONNECTIONS AND AUTHENTICATION
# ------------------------------------------------------------------------------
listen_addresses = '*'
max_connections = 100
shared_buffers = 256MB
effective_cache_size = 768MB
maintenance_work_mem = 64MB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 4MB
min_wal_size = 1GB
max_wal_size = 4GB

# ------------------------------------------------------------------------------
# LOGGING
# ------------------------------------------------------------------------------
logging_collector = on
log_directory = '/var/log/postgresql'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_rotation_age = 1d
log_rotation_size = 100MB
log_truncate_on_rotation = off
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
log_timezone = 'Asia/Seoul'

# ------------------------------------------------------------------------------
# QUERY TUNING
# ------------------------------------------------------------------------------
log_min_duration_statement = 1000
log_duration = off
log_statement = 'none'

# ------------------------------------------------------------------------------
# ERROR REPORTING
# ------------------------------------------------------------------------------
log_min_messages = warning
log_min_error_statement = error
client_min_messages = notice

# ------------------------------------------------------------------------------
# STATISTICS
# ------------------------------------------------------------------------------
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.max = 10000
pg_stat_statements.track = all
